// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5bPYfzSiVgHlsUXSAMyREfhSILwRjgJQ',
    appId: '1:678427082505:web:2a771112efd9741a6f5dd8',
    messagingSenderId: '678427082505',
    projectId: 'detailedinfo-6fb45',
    authDomain: 'detailedinfo-6fb45.firebaseapp.com',
    storageBucket: 'detailedinfo-6fb45.appspot.com',
    measurementId: 'G-ZS95V4TWP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQmElFOxvdiwpprc8hdnC1bxCyOwW2Rtc',
    appId: '1:678427082505:android:8d7fee98d07080c96f5dd8',
    messagingSenderId: '678427082505',
    projectId: 'detailedinfo-6fb45',
    storageBucket: 'detailedinfo-6fb45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0vbJFPfS6h0ERrzpRi7hPk8ACGOm5Dmw',
    appId: '1:678427082505:ios:e9fa2c57d897c05d6f5dd8',
    messagingSenderId: '678427082505',
    projectId: 'detailedinfo-6fb45',
    storageBucket: 'detailedinfo-6fb45.appspot.com',
    iosBundleId: 'com.example.detailInformation',
  );
}
